image: demurgos/haxe:3.1

before_script:
  - make prepare.haxelib

stages:
  - build
  - test
  - deploy

build-flash:
  stage: build
  script:
    - make build

test-flash:
  stage: test
  script:
    - make test
